site_name: Hypothesize
nav:
    - Home: index.md
    - Overview: overview.md
    - About: about.md
repo_name: <i class="fa fa-github"></i> Github
repo_url: https://github.com/Alcampopiano/hypothesize
edit_uri: ""
theme:
  name: cinder
  highlightjs: true

markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_css:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js